version: '3'
services:
  zeclight_flask_server:
    build: ./
    ports:
      - "3535:5050"
    hostname: zeclight_flask_server
    env_file:
    - .env
    container_name: zeclight_flask_server
    networks:
      - elemental_net
networks:
  elemental_net:
    external: true
    driver: bridge
